pipeline {
    agent any

    options {
        buildDiscarder(logRotator(numToKeepStr: '10'))
    }

    parameters {
        string name: 'REVISION',
            defaultValue: 'master',
            description: 'Revision to deploy'
    }

    environment {
        GCLOUD_PROJECT  = 'studied-beanbag-422111'
    }

    triggers {
        pollSCM('H/5 * * * *')
    }

    stages {
        stage('Source code checkout') {
            steps {
                script {
                    checkout scm
                }
            }
        }
        stage('Build') {
            steps {
                script {
                    withCredentials([file(credentialsId: 'main-key', variable: 'GOOGLE_APPLICATION_CREDENTIALS')]) {
                        dir('terraform') {
                            sh 'terraform init'
                            sh 'cat ${GOOGLE_APPLICATION_CREDENTIALS} > secret-key-file.json'
                            sh 'terraform apply -auto-approve'
                        }
                    }
                }
            }
        }
    }
}
